import Document, {Html, Head, Main, NextScript} from 'next/document'

class MyDocument extends Document{
    render(){
        return(
            <Html lang="en">
                <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                </Head>
                <body className="bg-[#f5f5f5] iransansweb" dir="rtl">
                    <Main />
                    <NextScript />
                </body>
            </Html>
        )
    }
}

export default MyDocument